---
- name: Ensure site_parent_dir directory exists.
  file:
    path: "{{ site_parent_dir }}"
    state: directory
    mode: 0775
    owner: "{{ site_os_user }}"
  become: yes
  when: not site_exists

- debug: msg="Installing Drupal with composer, in dir {{ site_parent_dir }}"

- name: Run composer install, this may take up to 5 minutes if your host OS is Windows
  command: >
    composer create-project drupal-composer/drupal-project:8.x-dev
    "{{ site_project_name }}"
    --stability dev
    chdir="{{ site_parent_dir }}"
    --no-interaction
  when: not site_exists
  become: no
  environment:
    COMPOSER_PROCESS_TIMEOUT: 2400

- name: Install dependencies with composer require.
  command: >
    {{ composer_path }} require {{ item }}
    chdir={{ site_parent_dir }}
  with_items: "{{ framework_composer_dependencies|default([]) }}"
  become: no
