---
- name: Ensure framework_composer_install_dir directory exists.
  file:
    path: "{{ framework_composer_install_dir }}"
    state: directory
    mode: 0775
    owner: "{{ site_os_user }}"
  become: yes
  when: framework_composer_path and not site_exists

#TDOO: check if there is a ready composer to use, or use recomended composer.json from drupal_composer
#composer create-project drupal-composer/drupal-project:8.x-dev my_project --stability dev --no-interaction

- debug: msg="Installing Drupal with composer, in dir {{ framework_composer_install_dir }}"

- name: Run composer install.
  command: >
    composer create-project drupal-composer/drupal-project:8.x-dev
    "{{ site_name }}"
    --stability dev
    chdir="{{ framework_composer_install_dir }}"
    --no-interaction

  when: not site_exists
  become: no


# Use copy-and-move to prevent issues in Windows with VirtualBox. See:
# https://github.com/ansible/ansible/issues/9526#issuecomment-62336962
- name: Copy composer.json into temporary location.
  copy:
    src: "{{ framework_composer_path }}"
    dest: "/tmp/genvm-composer.json"
  when: framework_composer_path and not site_exists
  become: no

- name: Move composer.json into place.
  command: "mv /tmp/genvm-composer.json {{ framework_composer_install_dir }}/composer.json"
  when: framework_composer_path and not site_exists
  become: no

#- name: Run composer install.
#  command: >
#    composer install
#    chdir={{ framework_composer_install_dir }}
#  when: not site_exists
#  become: no

# TODO composer create-project drupal-composer/drupal-project:8.x-dev my_project --stability dev --no-interaction

- name: Install dependencies with composer require.
  command: >
    {{ composer_path }} require {{ item }}
    chdir={{ framework_composer_install_dir }}
  with_items: "{{ framework_composer_dependencies|default([]) }}"
  become: no
