---
- name: Drupal Console:Check if Drupal Console is installed.
  stat: path={{ drupal_console_path }}
  register: drupal_bin

- name: Install Drupal Console.
  get_url:
    url: https://drupalconsole.com/installer
    dest: "{{ drupal_console_path }}"
  when: not drupal_bin.stat.exists

- name: Ensure Drupal Console is executable.
  file:
    path: "{{ drupal_console_path }}"
    mode: 0755