---
- name: Drush:Check if Drush is installed.
  stat: path=/usr/local/bin/drush
  register: drush_bin

- name: "Drush:Get Drush"
  command: php -r "readfile('https://s3.amazonaws.com/files.drush.org/drush.phar');" > /tmp/drush
  when: not drush_bin.stat.exists

- name: "Drush:Test installation Drush"
  command: php /tmp/drush core-status
  when: not drush_bin.stat.exists

- name: "Make drush executable"
  file: path=/tmp/drush mode=0555
  when: not drush_bin.stat.exists

- name: "Drush:move drush to /usr/local/bin/drush"
  command: mv /tmp/drush /usr/local/bin/drush
  when: not drush_bin.stat.exists
