---
- name: Drush:Check if Drush is installed.
  stat:
      path: "{{ drush_path }}"
  register: drush_bin

- name: Drush:Install Drush
  get_url:
    url: "{{ drush_phar_url }}"
    dest: "{{ drush_path }}"
  when: not drush_bin.stat.exists

- name: Ensure Drush is executable.
  file:
    path: "{{ drush_path }}"
    mode: 0755
  when: not drush_bin.stat.exists