---
- name: Drush:Check if Drush is installed.
  stat: path=/usr/local/bin/drush
  register: drush_bin

- name: "Drush:Get Drush"
  command: wget http://files.drush.org/drush.phar
  when: not drush_bin.stat.exists

- name: "Drush:Install Drush"
  command: php drush.phar core-status
  when: not drush_bin.stat.exists

- name: "Drush:move drush to /usr/local/bin/drush"
  command: mv drush.phar /usr/local/bin/drush
  when: not drush_bin.stat.exists
