---
- name: Check if Drupal is already set up.
  stat:
    path: "{{ site_document_root }}/index.php"
  register: drupal_site
  ignore_errors: true

- name: Define drupal_site_exists
  set_fact:
    drupal_site_exists: "{{ drupal_site.stat.exists|default(false) }}"

#- name: Verify VHosts directories exists
#  file: path="{{ item.path }}" state=directory mode=0755 owner="{{ site_os_user }}" group="users"
#  with_items: "{{ apache_vhosts }}"
#  notify: restart drupal

- name: Check if site is already installed.
  command: >
    drush status bootstrap
    chdir={{ site_document_root }}
  register: drupal_site_installed
  failed_when: "drupal_site_installed.stdout is undefined"
  changed_when: false
  become: no

- name: Install Drupal with drush.
  command: >
    drush site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ site_name }}"
    --account-name={{ site_username }}
    --account-pass={{ site_password }}
    --db-url=mysql://{{ db_user }}:{{ db_password }}@localhost/{{ db_database }}
    {{ drupal_site_install_extra_args | default([]) | join(" ") }}
    chdir={{ site_document_root }}
#  notify: restart webserver
  when: "'Successful' not in drupal_site_installed.stdout"
  become: no

- name: Install configured modules with drush.
  command: >
    {{ drush_path }} pm-enable -y {{ drupal_enable_modules | join(" ") }}
    chdir={{ drupal_core_path }}
  when: "'Successful' not in drupal_site_installed.stdout"
  become: no
