---
- include: drush.yml
- include: drupal_console.yml

- name: Check if Drupal is already set up
  stat: "path={{ site_document_root }}/index.php"
  register: drupal_site
  ignore_errors: true

- name: Define site_exists
  set_fact:
    site_exists: "{{ drupal_site.stat.exists|default(false) }}"

    # Build with composer if configured.
- include: composer_install.yml
  when: install_site

- include: install_site.yml
  when: install_site